### ISSUE TITLE
[Documentation] Missing srrg2_qgl_viewport

### ISSUE THREAD

**Issue by Dcasadoherraez** [digiamm/md_slam#1]
Thanks so much for the code release! Looking forward to trying it out 😄 

I was getting an error on during compilation that srrg2_qgl_viewport was not found.
Adding the line below fixed it for me
`
git clone https://gitlab.com/srrg-software/srrg2_qgl_viewport.git
`

**Comment by digiamm** [comment]
Hi @Dcasadoherraez, thank you. We explicitly write to build only `md_slam` in the workspace, which has the dependencies that we make you download. If you build the entire workspace then you may face issues of this type, because, for instance, the repo `srrg2_solver` contains many packages, one of these is `srrg2_solver_gui` which requires `srrg2_qgl_viewport`.  So either you exclude explicitly `srrg2_solver_gui` from compilation or you run `catkin build md_slam` as we write in the readme. We don't want you to download extra packages :innocent:
